name = "DirectLabel-pg0"
id = "8eea89ee"
widget_type = "l"
type = "script"
text = "l"

[properties]
widget_type = "l"
obj = "render2d/DirectLabel-pg0"
isCanvas = false
isLabel = true
specials_properties = [ "__UIEditorLabel__",]

[transform.position]
x = 0.0
y = 0.0
z = 0.5

[transform.rotation]
h = 0.0
p = 0.0
r = 0.0

[transform.scale]
x = 0.10000000149011612
y = 0.10000000149011612
z = 0.10000000149011612

[properties.specials.__UIEditorLabel__]
text = "test"
