id = "panda.egg"
name = "panda.egg"

[transform.position]
x = 0.0
y = 0.0
z = 0.0

[transform.rotation]
h = 0.0
p = 0.0
r = 0.0

[transform.scale]
x = 1.0
y = 1.0
z = 1.0

[properties.script_properties."D:/000PANDA3d-EDITOR/PANDA3D-EDITOR/script_inspector_example.py"]
node = "panda.egg"
rotation_h = "50000"
texture = "file:///D:/000PANDA3d-EDITOR/PANDA3D-EDITOR/Grass.png"
