name = "UI-Canvas"
id = "fd0ce0f1"
type = "script"

[properties]
isCanvas = true
isLabel = false
specials_properties = [ "__UIEditorLabel__",]

[transform.position]
x = 0.0
y = 0.0
z = 255.0

[transform.rotation]
h = 0.0
p = 0.0
r = 0.0

[transform.scale]
x = 1.0
y = 1.0
z = 1.0

[properties.specials.__UIEditorCanvas__]
