name = "UI-Canvas"
id = "7667597e"
widget_type = "c"
type = "script"
isCanvas = true
isLabel = false

[properties]
widget_type = "c"
specials_properties = [ "__UIEditorLabel__",]

[transform.position]
x = 0.0
y = 0.0
z = 255.0

[transform.rotation]
h = 0.0
p = 0.0
r = 0.0

[transform.scale]
x = 1.0
y = 1.0
z = 1.0

[properties.specials.__UIEditorCanvas__]
